services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bot_web
    command: gunicorn project.wsgi:application --bind 0.0.0.0:14009
    ports:
      - "14009:14009"
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - .:/app 
    environment:
      - DJANGO_SETTINGS_MODULE=project.settings

  worker:
    build:
      context: . 
      dockerfile: Dockerfile
    container_name: bot_celery_worker
    command: celery -A project worker --loglevel=info
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - .:/app 
    environment:
      - DJANGO_SETTINGS_MODULE=project.settings

  redis:
    image: redis:7-alpine
    container_name: bot_redis
    ports:
      - "6305:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
